football_management/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('users/', include('users.urls')),
    path('', include('football_management_app.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

football_management_app/urls.py
"Defines URL patterns for football_management_app."

from django.urls import path
from .views import TeamListView, TeamCreateView, GenerateMatchesView, MatchScheduleListView, MatchesListView, TeamUpdateView, TeamDeleteView
from .views import PlayerCreateView, PlayersListView, PlayerUpdateView, PlayerDeleteView
from django.views.generic import TemplateView
from django.contrib.admin.views.decorators import staff_member_required

app_name = 'football_management_app'
urlpatterns = [
    # Home page.
    path('', TemplateView.as_view(template_name='football_management_app/index.html'), name='index'),
    # Page that shows all teams.
    path('teams/', TeamListView.as_view(), name='teams_list'),
    # Page for adding a new team.
    path('team/add/', TeamCreateView.as_view(), name='new_team'),
    # Page for generate button.
    path('generate_matches/', staff_member_required(GenerateMatchesView.as_view()), name='generate_matches'),
    # Page for matche schedule.
    path('match_schedule/', MatchScheduleListView.as_view(), name='match_schedule'),
    # Page that shows all matches.
    path('match_list/', MatchesListView.as_view(), name='match_list'),
    # Updating team page.
    path('team/<int:pk>/', staff_member_required(TeamUpdateView.as_view()), name='team_update'),
    # Delete Team.
    path('team/<int:pk>/delete/', staff_member_required(TeamDeleteView.as_view()), name='team_delete'),
    # Creating a player.
    path('player/add/', PlayerCreateView.as_view(), name='new_player'),
    # Page with information about the players.
    path('players/', PlayersListView.as_view(), name='players_list'),
    # Updating player page.
    path('player/<int:pk>/', staff_member_required(PlayerUpdateView.as_view()), name='player_update'),
    # Delete Player.
    path('player/<int:pk>/delete/', staff_member_required(PlayerDeleteView.as_view()), name='player_delete')
]

users/urls.py
"""Defines URL patterns for users."""

from django.urls import path
from .views import RegisterView
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    # Login page.
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # Logout page.
    path("logout", auth_views.LogoutView.as_view(), name='logout'),
    # Registration page.
    path('register/', RegisterView.as_view(), name='register'),
]

football_management_app/models.py
from django.db import models

class Team(models.Model):
    name = models.CharField(max_length=30)
    date_added = models.DateTimeField(auto_now_add=True)

    
    def __str__(self):
        return self.name


class Match(models.Model):
    visitor = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='visitor')
    host = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='host')
    date = models.DateField()


class Player(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=300)
    photo = models.ImageField(upload_to='media')
    number = models.IntegerField()

users/models.py
from django.db import models

# Create your models here.

football_management_app/forms.py
from django import forms
from .models import Player


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['team', 'name', 'description', 'photo', 'number']

football_management_app/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from .models import Team, Match, Player
from .generating import generate_matches
from django.urls import reverse_lazy
from .forms import PlayerForm


class TeamListView(ListView):
    model = Team


class TeamCreateView(CreateView):
    model = Team
    fields = ['name']
    success_url = reverse_lazy('football_management_app:teams_list')


class GenerateMatchesView(TemplateView):
    def post(self, request):
        Match.objects.all().delete()
        generate_matches(Team.objects.all())
        return redirect('football_management_app:match_schedule')
    template_name = 'football_management_app/generate_matches.html'


class MatchScheduleListView(ListView):
    model = Match
    template_name = 'football_management_app/match_schedule.html'


class MatchesListView(ListView):
    model = Match


class TeamUpdateView(UpdateView):
    model = Team
    fields = ['name']
    success_url = reverse_lazy('football_management_app:teams_list')
    template_name = 'football_management_app/team_update.html'


class TeamDeleteView(DeleteView):
    model = Team
    success_url = reverse_lazy('football_management_app:teams_list')


class PlayersListView(ListView):
    paginate_by = 2
    model = Player
    template_name = 'football_management_app/player_list.html'


class PlayerCreateView(FormView):
    template_name = 'football_management_app/new_player.html'
    form_class = PlayerForm
    success_url = reverse_lazy('football_management_app:players_list')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class PlayerUpdateView(UpdateView):
    model = Player
    fields = ['name', 'description', 'number', 'photo']
    success_url = reverse_lazy('football_management_app:players_list')
    template_name = 'football_management_app/player_update.html'


class PlayerDeleteView(DeleteView):
    model = Player
    success_url = reverse_lazy('football_management_app:players_list')

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('football_management_app:index')
    template_name = 'registration/register.html'

football_management_app/templates/football_management_app/base.html
<!DOCTYPE html>
<html>
<head>
<style>
  * {
    box-sizing: border-box;
  }
  
  body {
    font-family: Arial;
    padding: 10px;
    background: #f1f1f1;
  }
  
  .header {
    padding: 30px;
    text-align: center;
  }
  
  .header h1 {
    font-size: 50px;
  }
  
  .header p{
    text-align: left;
  }
  
  .topnav {
    overflow: hidden;
    background-color: #333;
  }
  
  .topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }
  
  .topnav a:hover {
    background-color: white;
    color: black;
  }
  
  .button {
    background-color: #333; 
    color: #f2f2f2; 
    padding: 10px 20px; 
    text-align: center; 
    text-decoration: none; 
    display: inline-block;
  }
</style>
</head>

<body>
<div class="header">
  <h1>Football Management Application</h1>
</div>

<div class="topnav">
  <a href="{% url 'football_management_app:index' %}">Home</a> 
  {% if user.is_authenticated %}
    <a href="{% url 'users:logout' %}" style="float:right">Log out</a>
  {% else %}
    <a href="{% url 'users:register' %}" style="float:right">Register</a> 
    <a href="{% url 'users:login' %}" style="float:right">Log in</a>
  {% endif %}
  <a href="{% url 'football_management_app:teams_list' %}">Teams</a> 
  <a href="{% url 'football_management_app:players_list' %}">Players</a> 
  <a href="{% url 'football_management_app:new_player' %}">Add new player</a> 
  <a href="{% url 'football_management_app:generate_matches' %}">Generate Matches</a> 
  <a href="{% url 'football_management_app:match_schedule' %}">Match Schedule</a> 
  <a href="{% url 'football_management_app:match_list' %}">Match List</a>
</div>

{% block content %}{% endblock content %}
</body>

football_management_app/templates/football_management_app/generate_matches.html
{% extends "football_management_app/base.html" %}

{% block content %}
  <form method='post'>
    {% csrf_token %}
    <button name="submit">Generate matches</button>
  </form>

{% endblock content %}

football_management_app/templates/football_management_app/index.html
{% extends "football_management_app/base.html" %}

{% block content %}
<div class="header">
  <p>The Football Management application allows users to create a database of desired football teams, manage them and schedule their matches. <br>Adding a new team is made easy - only with a click of a button.<br>
  The app lets users generate match schedules, by randomly picking the opponents from the available list, making sure that each team is scheduled for a game only once a day.</p>
  <p> <strong>User guide:</strong><br>
    - To add a new team to the database click “Add a new team” under “Football Management”.<br>
    - Under “Teams” the user can see the list of all available teams at the moment.<br>
    - In the “Generate Matches” tab the user can create a random match schedule by clicking the button.<br>
    - Under “Match schedule” the user can see the already generated schedule.<br>
    - Summary of all planed games can be found under “Match list”.
  </p>
  <p> <strong>Developers guide (Prerequisites):</strong><br>
    - Python<br>
    - Django
  </p>
</div>
  <a href="team/add/" style="background-color: #333; color: #f2f2f2; padding: 14px 25px; text-align: center; text-decoration: 
  none; display: inline-block;">Add a new team</a>

<address style="text-align: right; margin-top:100px;">The product is web-based, no additional installation is required.</address>


{% endblock content %}

football_management_app/templates/football_management_app/match_list.html
{% extends "football_management_app/base.html" %}

{% block content %}

  <p>Matches:</p>

  <ul>
    {% for match in object_list %}
      <li> {{match.visitor}} - {{match.host}} </li>
    {% empty %}
      <li>No matches have been generated yet.</li>
    {% endfor %}
  </ul>

{% endblock content %}

football_management_app/templates/football_management_app/match_schedule.html
{% extends "football_management_app/base.html" %}

{% block content %}

  <p>Match Schedule:</p>

  <ul>
    {% for match in object_list %}
      <li> {{match.date}}: {{match.visitor}} - {{match.host}} </li>
    {% empty %}
      <li>No matches have been generated yet.</li>
    {% endfor %}
  </ul>

{% endblock content %}

football_management_app/templates/football_management_app/new_player.html
{% extends "football_management_app/base.html" %}

{% block content %}
  <p>Add a new player:</p>

  <form action="{% url 'football_management_app:new_player' %}" method='post' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" class="button">Add player</button>
  </form>

{% endblock content %}

football_management_app/templates/football_management_app/new_team.html
{% extends "football_management_app/base.html" %}

{% block content %}
  <p>Add a new team:</p>

  <form action="{% url 'football_management_app:new_team' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" class="button">Add team</button>
  </form>

{% endblock content %}

football_management_app/templates/football_management_app/player_list.html
{% extends "football_management_app/base.html" %}

{% block content %}

  <p>Players:</p>
  <head>
    <title>Players table:</title>
    <style>

      table, tr, th, td {
        text-align: center;
        border:2px solid black;
        border-collapse:collapse;
      }
      th {
        background-color: #333; 
        color: #f2f2f2;
        font-weight: normal;
      }
      table {
        width: 100%;
      }
      .pagination {
        text-align: right; margin-top:50px;
      }

    </style>
  </head>
  <body>
      <table> 
        <tr>
          <th style="width: 90px;">Name</th>
          <th>Description</th>
          <th>Number</th>
          <th>Photo</th>
          <th>Delete player</th>
        </tr>
        {% for player in object_list %}
        <tr>
          <td>
            <a href="{% url 'football_management_app:player_update' player.id %}">{{ player.name }}</a>
          </td>
          <td style="text-align: left;">{{ player.description }}</td>
          <td>{{ player.number }}</td>
          <td><img src="{{ player.photo.url }}" height="200" width="200"></td>
          <td>
            <form action="{% url 'football_management_app:player_delete' player.id %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit" class="button">Delete player</button>
            </form>
          </td>
        </tr>
    {% endfor %}
      </table>
  </body>

<div class="pagination">
    <span class="step-links">
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span><br>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a> -
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
                {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a> -
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

football_management_app/templates/football_management_app/player_update.html
{% extends "football_management_app/base.html" %}

{% block content %}

  <p>Edit player:</p>

  <form method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

football_management_app/templates/football_management_app/team_form.html
{% extends "football_management_app/base.html" %}

{% block content %}
  <p>Add a new team:</p>

  <form action="{% url 'football_management_app:new_team' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add team</button>
  </form>

{% endblock content %}

football_management_app/templates/football_management_app/team_list.html
{% extends "football_management_app/base.html" %}

{% block content %}
  <p>Teams:</p>

  <ul>
    {% for team in object_list %}
      <li>
        <a href="{% url 'football_management_app:team_update' team.id %}">{{ team }}</a>
          <form action="{% url 'football_management_app:team_delete' team.id %}" method='post'>
          {% csrf_token %}
          {{ form.as_p }}
          <button name="submit" class="button">Delete team</button>
          </form>
    {% empty %}
      <li>No teams have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

football_management_app/templates/football_management_app/team_update.html
{% extends "football_management_app/base.html" %}

{% block content %}

  <p>Edit team:</p>

  <form method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

football_management_app/templates/football_management_app/teams.html
{% extends "football_management_app/base.html" %}

{% block content %}

  <p>Teams:</p>

  <ul>
    {% for team in teams %}
      <li>{{ team }}</li>
    {% empty %}
      <li>No teams have been added yet.</li>
    {% endfor %}
  </ul>

{% endblock content %}